package cn.user9527.mycommunity.mapper;

import cn.user9527.mycommunity.model.Tar;
import cn.user9527.mycommunity.model.TarExample;

import java.util.List;

import cn.user9527.mycommunity.model.TarType;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface TarMapper {

    @Select("select id, tar_name,typt_id from tar where typt_id = #{id}")
    List<Tar> selectTar(Integer id);


    List<Tar> selectByIdTar(int[] id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    long countByExample(TarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    int deleteByExample(TarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    int insert(Tar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    int insertSelective(Tar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    List<Tar> selectByExample(TarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tar record, @Param("example") TarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    int updateByExample(@Param("record") Tar record, @Param("example") TarExample example);
}
