package cn.user9527.mycommunity.mapper;

import cn.user9527.mycommunity.model.TarType;
import cn.user9527.mycommunity.model.TarTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface TarTypeMapper {
    /**
     * 返回类型
     * @return
     */
    @Select("select id, type_name from tartype")
    List<TarType> selectTarType();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tartype
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    long countByExample(TarTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tartype
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    int deleteByExample(TarTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tartype
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    int insert(TarType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tartype
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    int insertSelective(TarType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tartype
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    List<TarType> selectByExample(TarTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tartype
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") TarType record, @Param("example") TarTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tartype
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    int updateByExample(@Param("record") TarType record, @Param("example") TarTypeExample example);
}
