package cn.user9527.mycommunity.model;

import java.util.ArrayList;
import java.util.List;

public class TarExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    public TarExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTarNameIsNull() {
            addCriterion("tar_name is null");
            return (Criteria) this;
        }

        public Criteria andTarNameIsNotNull() {
            addCriterion("tar_name is not null");
            return (Criteria) this;
        }

        public Criteria andTarNameEqualTo(String value) {
            addCriterion("tar_name =", value, "tarName");
            return (Criteria) this;
        }

        public Criteria andTarNameNotEqualTo(String value) {
            addCriterion("tar_name <>", value, "tarName");
            return (Criteria) this;
        }

        public Criteria andTarNameGreaterThan(String value) {
            addCriterion("tar_name >", value, "tarName");
            return (Criteria) this;
        }

        public Criteria andTarNameGreaterThanOrEqualTo(String value) {
            addCriterion("tar_name >=", value, "tarName");
            return (Criteria) this;
        }

        public Criteria andTarNameLessThan(String value) {
            addCriterion("tar_name <", value, "tarName");
            return (Criteria) this;
        }

        public Criteria andTarNameLessThanOrEqualTo(String value) {
            addCriterion("tar_name <=", value, "tarName");
            return (Criteria) this;
        }

        public Criteria andTarNameLike(String value) {
            addCriterion("tar_name like", value, "tarName");
            return (Criteria) this;
        }

        public Criteria andTarNameNotLike(String value) {
            addCriterion("tar_name not like", value, "tarName");
            return (Criteria) this;
        }

        public Criteria andTarNameIn(List<String> values) {
            addCriterion("tar_name in", values, "tarName");
            return (Criteria) this;
        }

        public Criteria andTarNameNotIn(List<String> values) {
            addCriterion("tar_name not in", values, "tarName");
            return (Criteria) this;
        }

        public Criteria andTarNameBetween(String value1, String value2) {
            addCriterion("tar_name between", value1, value2, "tarName");
            return (Criteria) this;
        }

        public Criteria andTarNameNotBetween(String value1, String value2) {
            addCriterion("tar_name not between", value1, value2, "tarName");
            return (Criteria) this;
        }

        public Criteria andTyptIdIsNull() {
            addCriterion("typt_id is null");
            return (Criteria) this;
        }

        public Criteria andTyptIdIsNotNull() {
            addCriterion("typt_id is not null");
            return (Criteria) this;
        }

        public Criteria andTyptIdEqualTo(Integer value) {
            addCriterion("typt_id =", value, "typtId");
            return (Criteria) this;
        }

        public Criteria andTyptIdNotEqualTo(Integer value) {
            addCriterion("typt_id <>", value, "typtId");
            return (Criteria) this;
        }

        public Criteria andTyptIdGreaterThan(Integer value) {
            addCriterion("typt_id >", value, "typtId");
            return (Criteria) this;
        }

        public Criteria andTyptIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("typt_id >=", value, "typtId");
            return (Criteria) this;
        }

        public Criteria andTyptIdLessThan(Integer value) {
            addCriterion("typt_id <", value, "typtId");
            return (Criteria) this;
        }

        public Criteria andTyptIdLessThanOrEqualTo(Integer value) {
            addCriterion("typt_id <=", value, "typtId");
            return (Criteria) this;
        }

        public Criteria andTyptIdIn(List<Integer> values) {
            addCriterion("typt_id in", values, "typtId");
            return (Criteria) this;
        }

        public Criteria andTyptIdNotIn(List<Integer> values) {
            addCriterion("typt_id not in", values, "typtId");
            return (Criteria) this;
        }

        public Criteria andTyptIdBetween(Integer value1, Integer value2) {
            addCriterion("typt_id between", value1, value2, "typtId");
            return (Criteria) this;
        }

        public Criteria andTyptIdNotBetween(Integer value1, Integer value2) {
            addCriterion("typt_id not between", value1, value2, "typtId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tar
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 14 10:03:15 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tar
     *
     * @mbg.generated Mon Oct 14 10:03:15 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}